# Generated by Django 4.2 on 2023-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
