# Generated by Django 4.2 on 2023-04-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_personinitials_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonInitials',
        ),
    ]
