# Generated by Django 4.2 on 2023-04-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_delete_person_delete_personinitials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
