# Generated by Django 4.2 on 2023-04-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
